version: '3.4'
services:
  netbox: &netbox
    restart: unless-stopped
    image: netboxcommunity/netbox:${VERSION-latest-ldap}
    depends_on:
    - redis
    - redis-cache
    - netbox-worker
    user: '101'
    env_file: /srv/netbox/env/netbox.env
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ./initializers:/opt/netbox/initializers:z,ro
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-nginx-config:/etc/netbox-nginx:z
    - netbox-static-files:/opt/netbox/netbox/static:z
    - netbox-media-files:/opt/netbox/netbox/media:z
    - /etc/ssl/certs/ffho-cacert.pem:/etc/ssl/certs/ffho-cacert.pem
    - /etc/ssl/certs/d7778ef0.0:/etc/ssl/certs/d7778ef0.0
    - /etc/ssl/certs/1215c584.0:/etc/ssl/certs/1215c584.0
    - /srv/netbox/scripts/:/etc/netbox/scripts:z,ro
  netbox-worker:
    <<: *netbox
    restart: unless-stopped
    depends_on:
    - redis
    entrypoint:
    - python3
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker

  # nginx
  nginx:
    restart: unless-stopped
    command: nginx -c /etc/netbox-nginx/nginx.conf
    image: nginx:1.19-alpine
    depends_on:
    - netbox
    ports:
    - 127.0.0.1:8001:8080
    volumes:
    - netbox-static-files:/opt/netbox/netbox/static:ro
    - netbox-nginx-config:/etc/netbox-nginx/:ro

  # redis
  redis:
    restart: unless-stopped
    image: redis:6-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: /srv/netbox/env/redis.env
    volumes:
    - netbox-redis-data:/data
  redis-cache:
    restart: unless-stopped
    image: redis:6-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis-cache.env

volumes:
  netbox-static-files:
    driver: local
  netbox-nginx-config:
    driver: local
  netbox-media-files:
    driver: local
  netbox-redis-data:
    driver: local
